### ISSUE TITLE
INFO: CryticCompile: 'npx buidler compile' running

### ISSUE THREAD

**Issue by PaulRBerg** [crytic/crytic-compile#115]
## Description

I ran the following steps:

1. Install Echidna via [Docker](https://github.com/crytic/building-secure-contracts/tree/master/program-analysis/echidna#installation)
2. Add `cryticArgs: ["--compile-force-framework", "buidler"]` in my `config.yml` file
3. Execute `echidna-test ./contracts/invariants/FintrollerInvariants.sol --config ./contracts/invariants/config.yml`

And received the error below.

## Error
```
ethsec@dd7de7baf69b:/home/workspace$ echidna-test ./contracts/invariants/FintrollerInvariants.sol --config ./contracts/invariants/config.yml
echidna-test: Couldn't compile given file
stdout:
stderr:
INFO:CryticCompile:'npx buidler compile' running
Traceback (most recent call last):
  File "/home/ethsec/.local/bin/crytic-compile", line 33, in <module>
    sys.exit(load_entry_point('crytic-compile==0.1.9', 'console_scripts', 'crytic-compile')())
  File "/home/ethsec/.local/lib/python3.6/site-packages/crytic_compile/__main__.py", line 157, in main
    compilations = compile_all(**vars(args))
  File "/home/ethsec/.local/lib/python3.6/site-packages/crytic_compile/crytic_compile.py", line 1019, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/home/ethsec/.local/lib/python3.6/site-packages/crytic_compile/crytic_compile.py", line 123, in __init__
    self._compile(**kwargs)
  File "/home/ethsec/.local/lib/python3.6/site-packages/crytic_compile/crytic_compile.py", line 930, in _compile
    self._platform.compile(self, **kwargs)
  File "/home/ethsec/.local/lib/python3.6/site-packages/crytic_compile/platform/buidler.py", line 66, in compile
    cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, cwd=self._target
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
NotADirectoryError: [Errno 20] Not a directory: './contracts/invariants/FintrollerInvariants.sol'
```

## Environment

+ node@v12.16.3
+ yarn@1.22.10
+ npm@6.14.4
+ echidna@1.5.1
+ buidler@1.4.7

**Comment by PaulRBerg** [comment]
It looks like a bug to me. I changed the command to:

```sh
echidna-test . --contract FintrollerInvariants --config contracts/invariants/config.yml
```

And now I'm getting this error:

```sh
echidna-test: Couldn't compile given file
stdout:
stderr:
INFO:CryticCompile:'npx buidler compile' running
INFO:CryticCompile:Compiling...
Downloading compiler version 0.7.4
Compiled 41 contracts successfully

ERROR:CryticCompile:Unknown file: ontracts/BalanceSheet.sol
```

Is it because [I'm using solidity 0.7.4][1], while the [eth-security-toolbox][2] only accepts up to 0.7.2?

[1]: https://github.com/MainframeHQ/mainframe-lending-protocol/blob/1330aa3dea3b45ec984bf8f929e0516c72339c06/buidler.config.ts#L133
[2]: https://github.com/crytic/eth-security-toolbox

**Comment by PaulRBerg** [comment]
Nah, it's not about the compiler version. I downgrade to 0.7.2 and the above errors persists.

**Comment by PaulRBerg** [comment]
Closing in favour of #116.
