### ISSUE TITLE
crytic_compile error

### ISSUE THREAD

**Issue by Alipipe** [crytic/crytic-compile#161]
macos, python3.7.1, crytic-compile0.1.12

% crytic-compile examples/solidity/basic/flags.sol

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/crytic-compile", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/crytic_compile/__main__.py", line 157, in main
    compilations = compile_all(**vars(args))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/crytic_compile/crytic_compile.py", line 1076, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/crytic_compile/crytic_compile.py", line 137, in __init__
    self._compile(**kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/crytic_compile/crytic_compile.py", line 987, in _compile
    self._platform.compile(self, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/crytic_compile/platform/solc.py", line 180, in compile
    crytic_compile.abis[contract_name] = json.loads(info["abi"])
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not list

**Comment by Alipipe** [comment]
i retry on centos7, and i got some warning but no Exception; it means compatibility issue?

**Comment by Alipipe** [comment]
i resolve it by this way:
vim /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/crytic_compile/platform/solc.py
goto line180

crytic_compile.abis[contract_name] = json.loads(info["abi"]) => crytic_compile.abis[contract_name] = (info["abi"])
userdoc = json.loads(info.get("userdoc", "{}")) => userdoc = info.get("userdoc", "{}")
userdoc = json.loads(info.get("userdoc", "{}")) => userdoc = info.get("userdoc", "{}")

retry the execute cmd,it works now. wtf!

**Comment by montyly** [comment]
Hi @Alipipe.

Thank you for reporting this. What version of solc are you using? 

We recently improved the support for 0.8, which looks like the issue you encountered: https://github.com/crytic/crytic-compile/pull/147/files
