### ISSUE TITLE
Compilation of multiple (dependent) solidity files

### ISSUE THREAD

**Issue by CodeGodz** [crytic/crytic-compile#257]
Let's take these two simple contracts:

<h3>Contracts</h3>

**`ContractA.sol`:**
```solidity
pragma solidity ^0.8.0;
contract ContractA {
    uint public x;
    constructor(uint y) public {
        x = y;
    }
}
```
**`ContractB.sol`:**
```solidity
pragma solidity ^0.8.0;
import "./ContractA.sol";
contract ContractB {
    ContractA x;
    constructor() public {
        x = new ContractA(10);
    }
}
```

<h3>Goal: Slither</h3>
I want to compile this such that I can use it in Slither, like 

```python 
x = Slither(CryticCompile('contracts_test/ContractA.sol')) # <- but then both ContractA and contractB
```

<h3>Py-solc-x</h3>
Compilation works fine when I pass it to `py-solc-x` to compile:

```python
compy = solcx.compile_files(
    glob('contracts_test/*.sol'),
    solc_version="0.8.0",
    output_values=["abi", "bin-runtime"])
``` 
<h3>Tries CryticCompile</h3>

However I cannot get this to compile with CryticCompile. 

_**Compile all**_
I found [this piece of code](https://github.com/crytic/crytic-compile/blob/35d95d6cb7716290ff4bf21ba9dcc8e582c6ee04/crytic_compile/crytic_compile.py#L606-L662) so I tried:
```python 
compy = compile_all(glob('contracts_test/*.sol'), solc_solcs_bin=..)
```
But this throws 
```
Traceback (most recent call last):
  File "/home/codegodz/PycharmProjects/AstraX/bin.py", line 43, in <module>
    compy = compile_all(glob('contracts_test/*.sol'), solc_solcs_bin={file.split('/')[-1].replace('solc-', ''): file for file in glob('/home/codegodz/.solc-select/artifacts/' + 'solc-*')})
  File "/home/codegodz/.local/lib/python3.8/site-packages/crytic_compile/crytic_compile.py", line 623, in compile_all
    globbed_targets = glob.glob(target, recursive=True)
  File "/usr/lib/python3.8/glob.py", line 21, in glob
    return list(iglob(pathname, recursive=recursive))
  File "/usr/lib/python3.8/glob.py", line 42, in _iglob
    dirname, basename = os.path.split(pathname)
  File "/usr/lib/python3.8/posixpath.py", line 103, in split
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not list
```

_**Standalone**_
I thought maybe I can do something like this
```python
compilation_unit = CompilationUnit(CryticCompile(XXX, "test"))
compilation_unit.compiler_version = CompilerVersion(compiler="solc", version="0.8.0", optimized=True, optimize_runs=200)
standalone_compile(glob('contracts_test/*.sol'), compilation_unit)
```
However I wasn't sure how to properly initialize `crytic_compile` to pass to `CompilationUnit`, plus that this does not return the `CryticCompile` object I need to init with Slither.

<h4> Questions </h4>

So I wonder how I can use multiple `.sol` files with dependencies in Slither directly or indirectly. Since this all goes via CrytiCompile I created the issue here. 

- I suspect there is an easy way of passing the `.sol` files just like in `py-solc` that I'm missing?
- or ,if not, is there a way to directly use the compilation results from `py-solc-x` to create the CryticCompile object (like providing the bytecode, abi, optimizer as done for Etherscan)

**Comment by CodeGodz** [comment]
Unrelated to my question but I see the same error gets thrown for [this single file contract](https://bscscan.com/address/0x24d8AE8Dd8AdE72A1c37De260Bb90306c7160bF2#code) whereas compiling with `py-solc-x` works fine again

**Comment by CodeGodz** [comment]
Aaah this works if I only pass the contract that is dependent, `ContractB` to CryticCompile
