### ISSUE TITLE
KeyError 'bytecode' when running `slither .` with Foundry

### ISSUE THREAD

**Issue by pedrommaiaa** [crytic/crytic-compile#266]
As the title says.

```
Traceback (most recent call last):
  File "/Users/usr/project/env/lib/python3.10/site-packages/slither/__main__.py", line 744, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/Users/usr/project/env/lib/python3.10/site-packages/slither/__main__.py", line 76, in process_all
    compilations = compile_all(target, **vars(args))
  File "/Users/usr/project/env/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/Users/usr/project/env/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/Users/usr/project/env/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/Users/usr/project/env/lib/python3.10/site-packages/crytic_compile/platform/foundry.py", line 137, in compile
    compilation_unit.bytecodes_init[contract_name] = target_loaded["bytecode"][
KeyError: 'bytecode'
None
Error in .
```

**Comment by pedrommaiaa** [comment]
@0xalpharush Yeah I closed it in favor of compiling it with hardhat but I still run into an error when trying both ways:

running `slither . --compile-force-framework foundry `:
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/pedromaia/rari/fuse-v1/env/lib/python3.10/site-packages/slither/__main__.py", line 744, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/Users/pedromaia/rari/fuse-v1/env/lib/python3.10/site-packages/slither/__main__.py", line 76, in process_all
    compilations = compile_all(target, **vars(args))
  File "/Users/pedromaia/rari/fuse-v1/env/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/Users/pedromaia/rari/fuse-v1/env/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/Users/pedromaia/rari/fuse-v1/env/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/Users/pedromaia/rari/fuse-v1/env/lib/python3.10/site-packages/crytic_compile/platform/foundry.py", line 124, in compile
    raise InvalidCompilation(txt)
crytic_compile.platform.exceptions.InvalidCompilation: Unknown file: src/external/compound/Comptroller.sol
```

with hardhat `slither .`:
```
    parser.parse_top_level_from_loaded_json(ast, path)
  File "/Users/pedromaia/rari/fuse-v1/env/lib/python3.10/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 238, in parse_top_level_from_loaded_json
    _handle_import_aliases(symbol_aliases, import_directive, scope)
  File "/Users/pedromaia/rari/fuse-v1/env/lib/python3.10/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 50, in _handle_import_aliases
    and "name" in symbol_alias["foreign"]
TypeError: argument of type 'int' is not iterable
```

running `slither src/` says that it can't find the openZappelin library even though the tests with foundry and hardhat work fine.
```
crytic_compile.platform.exceptions.InvalidCompilation: Invalid solc compilation Error: Source "@openzeppelin/contracts-upgradeable/proxy/Initializable.sol" not found: File not found.
 --> src/FusePoolLensSecondary.sol:5:1:
  |
5 | import "@openzeppelin/contracts-upgradeable/proxy/Initializable.sol";
```

The above could have something todo with this issue: https://github.com/crytic/slither/issues/1226

**Comment by pedrommaiaa** [comment]
Closing this in favor of https://github.com/crytic/crytic-compile/issues/270.
