### ISSUE TITLE
Bug: Echidna doesn't detect compilation errors when there are older compiled contracts available

### ISSUE THREAD

**Issue by rappie** [crytic/crytic-compile#268]
I have only tested this using hardhat.

How to reproduce:
* Set up a working echidna fuzzing campaign
* Add a syntax error to one of the contracts. Ex. `echo "}" > contracts/simple.sol`
* Run echidna with the same command. This should not work but works with the old code.
* Run `npx hardhat clean` to remove older compiled contracts
* Run echidna again. Now it crashes with `echidna-test: Couldn't compile given file` (and a lot more stuff)

This bug is actually a lot more annoying than it looks at first sight. I've had many times where I spent like 15 minutes trying to figure out why echidna doesnt find anything when it turned out I had a simple syntax error somewhere else in my code.

**Comment by rappie** [comment]
Maybe this helps:

Compiling with hardhat gives a compilation error
```
$ npx hardhat compile
DeclarationError: Undeclared identifier.
  --> contracts/Target.sol:11:14:
   |
11 |         emit SenderAddress(msg.sender);
   |              ^^^^^^^^^^^^^


Error HH600: Compilation failed

For more info go to https://hardhat.org/HH600 or run Hardhat with --show-stack-traces
```

Crytic compile shows the same compilation error but doesn't seem to handle it well
```
$ crytic-compile .
INFO:CryticCompile:'npx hardhat compile --force' running
INFO:CryticCompile:

ERROR:CryticCompile:DeclarationError: Undeclared identifier.
  --> contracts/Target.sol:11:14:
   |
11 |         emit SenderAddress(msg.sender);
   |              ^^^^^^^^^^^^^


Error HH600: Compilation failed
For more info go to https://hardhat.org/HH600 or run Hardhat with --show-stack-traces

Traceback (most recent call last):
  File "/home/rappie/.local/bin/crytic-compile", line 8, in <module>
    sys.exit(main())
  File "/home/rappie/.local/lib/python3.10/site-packages/crytic_compile/__main__.py", line 192, in main
    compilations = compile_all(**vars(args))
  File "/home/rappie/.local/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/home/rappie/.local/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/home/rappie/.local/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/home/rappie/.local/lib/python3.10/site-packages/crytic_compile/platform/hardhat.py", line 92, in compile
    os.listdir(build_directory), key=lambda x: os.path.getmtime(Path(build_directory, x))
FileNotFoundError: [Errno 2] No such file or directory: 'artifacts/build-info'
```

Let me know if you want a seperate issue for this
