### ISSUE TITLE
It cannot Find Imported and Installed OpenZeppelin Libraries.

### ISSUE THREAD

**Issue by Nachoxt17** [crytic/crytic-compile#280]
- Hello, I receive this Error when Trying to Compile my Solidity S.C. for after that Analyzing it with Slither:
```
Error: Source "@openzeppelin/contracts/utils/Counters.sol" not found: File not found.
 --> ./Creations.sol:5:1:
  |
5 | import "@openzeppelin/contracts/utils/Counters.sol";
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Error: Source "@openzeppelin/contracts/security/ReentrancyGuard.sol" not found: File not found.
 --> ./Creations.sol:8:1:
  |
8 | import "@openzeppelin/contracts/security/ReentrancyGuard.sol";
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Error: Source "@openzeppelin/contracts/token/ERC1155/ERC1155.sol" not found: File not found.
  --> ./Creations.sol:10:1:
   |
10 | import "@openzeppelin/contracts/token/ERC1155/ERC1155.sol";
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Error: Source "@openzeppelin/contracts/token/ERC1155/extensions/IERC1155MetadataURI.sol" not found: File not found.
  --> ./Creations.sol:11:1:
   |
11 | import "@openzeppelin/contracts/token/ERC1155/extensions/IERC1155MetadataURI.sol";
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Error: Source "@openzeppelin/contracts/token/ERC1155/utils/ERC1155Receiver.sol" not found: File not found.
  --> ./Creations.sol:12:1:
   |
12 | import "@openzeppelin/contracts/token/ERC1155/utils/ERC1155Receiver.sol";
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Error: Source "@openzeppelin/contracts/token/ERC20/IERC20.sol" not found: File not found.
  --> ./Creations.sol:13:1:
   |
13 | import "@openzeppelin/contracts/token/ERC20/IERC20.sol";
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


ERROR:CryticCompile:Invalid solc compilation Error: Source "@openzeppelin/contracts/utils/Counters.sol" not found: File not found.
 --> ./Creations.sol:5:1:
  |
5 | import "@openzeppelin/contracts/utils/Counters.sol";
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Error: Source "@openzeppelin/contracts/security/ReentrancyGuard.sol" not found: File not found.
 --> ./Creations.sol:8:1:
  |
8 | import "@openzeppelin/contracts/security/ReentrancyGuard.sol";
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Error: Source "@openzeppelin/contracts/token/ERC1155/ERC1155.sol" not found: File not found.
  --> ./Creations.sol:10:1:
   |
10 | import "@openzeppelin/contracts/token/ERC1155/ERC1155.sol";
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Error: Source "@openzeppelin/contracts/token/ERC1155/extensions/IERC1155MetadataURI.sol" not found: File not found.
  --> ./Creations.sol:11:1:
   |
11 | import "@openzeppelin/contracts/token/ERC1155/extensions/IERC1155MetadataURI.sol";
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Error: Source "@openzeppelin/contracts/token/ERC1155/utils/ERC1155Receiver.sol" not found: File not found.
  --> ./Creations.sol:12:1:
   |
12 | import "@openzeppelin/contracts/token/ERC1155/utils/ERC1155Receiver.sol";
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Error: Source "@openzeppelin/contracts/token/ERC20/IERC20.sol" not found: File not found.
  --> ./Creations.sol:13:1:
   |
13 | import "@openzeppelin/contracts/token/ERC20/IERC20.sol";
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
- All these Dependencies are Installed.

**Comment by elopez** [comment]
Hi @Nachoxt17, what framework (hardhat, foundry, etc) are you using and how are you calling crytic-compile or slither? Remember that if you intend to use your framework's dependency resolution, you should provide your project root folder as the target, and not a .sol file.

**Comment by Nachoxt17** [comment]
I use Hardhat and I solved the Problem by Copying and Pasting the @openzeppelin/contracts Folder to the Same Folder of my S.C.s and modifying. I run both `crytic-compile .` and `slither .` directly in the Folder of my S.C.s. because otherwise I get this Error:
```
INFO:CryticCompile:'npx hardhat compile --force' running
Traceback (most recent call last):
  File "/home/nachoxt17/.local/bin/crytic-compile", line 8, in <module>
    sys.exit(main())
  File "/home/nachoxt17/.local/lib/python3.8/site-packages/crytic_compile/__main__.py", line 192, in main
    compilations = compile_all(**vars(args))
  File "/home/nachoxt17/.local/lib/python3.8/site-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/home/nachoxt17/.local/lib/python3.8/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__   
    self._compile(**kwargs)
  File "/home/nachoxt17/.local/lib/python3.8/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile   
    self._platform.compile(self, **kwargs)
  File "/home/nachoxt17/.local/lib/python3.8/site-packages/crytic_compile/platform/hardhat.py", line 73, in compile   
    with subprocess.Popen(
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/c/Program Files/nodejs/npx'
```

**Comment by elopez** [comment]
Ah interesting, I see you are using WSL. Did you install node inside WSL as well? It appears it's trying to pick up something on the Windows path instead of the Linux path 🤔 Can you confirm if running `npx hardhat compile --force` on the WSL shell works?

**Comment by Nachoxt17** [comment]
No, it gives me this output:
```
$ npx hardhat compile --force
You are using a version of Node.js that is not supported by Hardhat, and it may work incorrectly, or not work at all.

Please, make sure you are using a supported version of Node.js.

To learn more about which versions of Node.js are supported go to https://hardhat.org/nodejs-versions
An unexpected error occurred:

TypeError: [userConfig.abiExporter].flat is not a function
    at /mnt/d/Work_Programming_Projects/Creations-Project/node_modules/hardhat-abi-exporter/index.js:37:49
    at loadConfigAndTasks (/mnt/d/Work_Programming_Projects/Creations-Project/node_modules/hardhat/src/internal/core/config/config-loading.ts:108:5) 
    at main (/mnt/d/Work_Programming_Projects/Creations-Project/node_modules/hardhat/src/internal/cli/cli.ts:180:62)
```

**Comment by elopez** [comment]
Mixing components between the operating systems is not something we tested; I'd recommend you go one of two ways to avoid problems:
* fully on WSL - you would do everything as if you were using the tools on a Linux system; start by installing Node and Python on WSL. You can install Node with e.g. [the Ubuntu instructions](https://github.com/nodesource/distributions/blob/master/README.md#debinstall) and Python with `apt`. Then install the crytic tools as usual with `pip3`, clone your project and install node modules with `npm` in the WSL terminal, run slither in the WSL terminal, etc.
* fully on Windows: you can download and install Windows versions of Node and Python. You can then use `pip3` from cmd or powershell to install slither and solc-select ([beta has Windows support](https://github.com/crytic/solc-select#unsupported-platform-on-windows)), and use all the tools natively from powershell / cmd.

**Comment by Nachoxt17** [comment]
Thanks
