### ISSUE TITLE
"rytic_compile.platform.exceptions.InvalidCompilation". Any solution for this error? I've been trying to solve it for almost 30 days and no support

### ISSUE THREAD

**Issue by joebb10** [crytic/crytic-compile#298]
```

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/slither/__main__.py", line 744, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/slither/__main__.py", line 76, in process_all
    compilations = compile_all(target, **vars(args))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 658, in compile_all
    compilations.append(CryticCompile(filename, **kwargs))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/crytic_compile/platform/solc.py", line 154, in compile
    targets_json = _get_targets_json(compilation_unit, self._target, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/crytic_compile/platform/solc.py", line 276, in _get_targets_json
    return _run_solc(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/crytic_compile/platform/solc.py", line 474, in _run_solc
    compiler="solc", version=get_version(solc, env), optimized=is_optimized(solc_arguments)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/crytic_compile/platform/solc.py", line 381, in get_version
    raise InvalidCompilation(f"Solidity version not found: {stdout}")
crytic_compile.platform.exceptions.InvalidCompilation: Solidity version not found: No solc version set. Run `solc-select use VERSION` or set SOLC_VERSION environment variable.

None
Error in .
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/slither/__main__.py", line 744, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/slither/__main__.py", line 76, in process_all
    compilations = compile_all(target, **vars(args))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 658, in compile_all
    compilations.append(CryticCompile(filename, **kwargs))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/crytic_compile/platform/solc.py", line 154, in compile
    targets_json = _get_targets_json(compilation_unit, self._target, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/crytic_compile/platform/solc.py", line 276, in _get_targets_json
    return _run_solc(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/crytic_compile/platform/solc.py", line 474, in _run_solc
    compiler="solc", version=get_version(solc, env), optimized=is_optimized(solc_arguments)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/crytic_compile/platform/solc.py", line 381, in get_version
    raise InvalidCompilation(f"Solidity version not found: {stdout}")
crytic_compile.platform.exceptions.InvalidCompilation: Solidity version not found: No solc version set. Run `solc-select use VERSION` or set SOLC_VERSION environment variable.
```

//  I have been trying to set the solc version and I'm still getting the same error when I try to run slither , echidna, solc-select or any other crytic command. I don't know what is happening but looks like the issue is on the artifacts. Any solution?

**Comment by 0xalpharush** [comment]
Do you have solc-select installed? If not, please run `pip install solc-slect`. Then, run `solc-select install all` or specify the solidity compiler version you have chosen in your contract. Once you've done that, you should be able to run crytic-compile. Note, that crytic-compile expects either a standalone solidity (`.sol`) file, `crytic-compile test.sol`, or a compilation framework like hardhat, foundry etc, `crytic-compile .` (run in the project directy).

**Comment by joebb10** [comment]
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/bin/solc-select", line 8, in <module>
    sys.exit(solc_select())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/solc_select/__main__.py", line 51, in solc_select
    install_artifacts(args.get(INSTALL_VERSIONS))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/solc_select/solc_select.py", line 45, in install_artifacts
    releases = get_available_versions()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/solc_select/solc_select.py", line 112, in get_available_versions
    list_json = urllib.request.urlopen(url).read()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 510, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 521, in _open
    result = self._call_chain(self.handle_open, 'default',
AttributeError: 'OpenerDirector' object has no attribute '_call_chain'
```

I ran it on a standalone solidity(.sol) file and got the same error when I ran "solc-select install all". And the "pip install solc-select" is already there. Any other solution?

**Comment by elopez** [comment]
After installing one or more solc versions, you will also need to select the solidity compiler version system-wide before running crytic-compile, by running `solc-select use 0.8.0` (replace 0.8.0 with the solc version you need to compile your contract)

**Comment by joebb10** [comment]
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/bin/solc-select", line 8, in <module>
    sys.exit(solc_select())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/solc_select/__main__.py", line 54, in solc_select
    switch_global_version(args.get(USE_VERSION))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/solc_select/solc_select.py", line 80, in switch_global_version
    elif version in get_available_versions():
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/solc_select/solc_select.py", line 112, in get_available_versions
    list_json = urllib.request.urlopen(url).read()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 510, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 521, in _open
    result = self._call_chain(self.handle_open, 'default',
AttributeError: 'OpenerDirector' object has no attribute '_call_chain'
```

Yeah, I've been trying it for the last 15 days I guess. Any other solution? I don't know what to do cause I can't run slither, echidna, etc. and none of them is working. Sometimes it works a few times and then we back to the same error...

**Comment by elopez** [comment]
Can you try with the latest solc-select release, version 1.0.1? You seem to be running an older one (0.2.1)

The stack traces look odd though, it is failing on a third party library (`urllib`) while doing a web request. If you still have trouble with it, I'd suggest either cleaning up your python installation and starting from scratch, or using a python virtual environment (venv).

You can also install slither, echidna, crytic-compile and solc-select using Homebrew, which as a side effect will use the Homebrew python installation on a clean environment.

**Comment by joebb10** [comment]
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/bin/solc-select", line 8, in <module>
    sys.exit(solc_select())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/solc_select/__main__.py", line 54, in solc_select
    switch_global_version(args.get(USE_VERSION))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/solc_select/solc_select.py", line 80, in switch_global_version
    elif version in get_available_versions():
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/solc_select/solc_select.py", line 112, in get_available_versions
    list_json = urllib.request.urlopen(url).read()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 510, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 521, in _open
    result = self._call_chain(self.handle_open, 'default',
AttributeError: 'OpenerDirector' object has no attribute '_call_chain'
```

Tried! and I got the same error again. If I use homebrew, should I run slither, echidna, etc. in the same way? if so, I believe I already did it

**Comment by elopez** [comment]
That stack trace is still from the older 0.2.1 version 🤔 

Answering your question, yes, `brew install echidna` and then run echidna normally. For the Python tools (solc-select, slither, crytic-compile) make sure to remove your non-homebrew installations first (eg the ones living in `/Library/Frameworks/Python.framework/Versions/3.10` you are executing now). You can use pip to uninstall those (make sure you are using the right pip from that installation and not the homebrew pip though)

**Comment by joebb10** [comment]
I'm running "solc-select use 1.0.1"  and still getting the same error. What I mean is that I'm not able to change the solc version either. When I tried to change running "solc-select use 1.0.1", this message appears on the terminal: 

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/bin/solc-select", line 8, in <module>
    sys.exit(solc_select())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/solc_select/__main__.py", line 54, in solc_select
    switch_global_version(args.get(USE_VERSION))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/solc_select/solc_select.py", line 80, in switch_global_version
    elif version in get_available_versions():
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/solc_select/solc_select.py", line 112, in get_available_versions
    list_json = urllib.request.urlopen(url).read()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 510, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 521, in _open
    result = self._call_chain(self.handle_open, 'default',
AttributeError: 'OpenerDirector' object has no attribute '_call_chain'
```
 
U can see that is the same error. I'm not able to change the solc version, run slither, echidna, etc. That's what I am talking about. You are asking me to change the version, right? Every time I've changed I got that error what makes me unable to change the solc version. Any other solution?

**Comment by elopez** [comment]
No, I meant upgrading solc-select, the program. You would need to run `pip3 install --upgrade solc-select` to upgrade to solc-select 1.0.1 (you now have solc-select 0.2.1 installed). Then try installing and selecting solc 0.8.0 (or whichever you need) with it (e.g. `solc-select use 0.8.0`)

If you still have the same `AttributeError: 'OpenerDirector' object has no attribute '_call_chain'` error after the upgrade, I would still recommend removing everything from your python installation and starting from scratch, using a venv, or using the brew packages. That crash is happening in `urllib` and not in the `solc-select` tool's code, so something is not right with your current Python install and environment.

**Comment by joebb10** [comment]
Hi! I uninstalled Python and installed again from scratch and now its working normally.
Thanks!
