### ISSUE TITLE
crytic_compile.platform.exceptions.InvalidCompilation: Unknown file: src/interfaces/ICostModel.sol

### ISSUE THREAD

**Issue by mds1** [crytic/crytic-compile#305]
Unfortunately the repo is not open source at the moment (though @0xicingdeath @rmi7 and @damilolaedwards currently have access), but I can summarize the folder structure that caused the issue:

- RootRepo has RepoModels as a submodule
- RepoModels has RepoInterfaces as a submodule
- All paths use "absolute" paths, e.g. `src/interfaces/ICostModel.sol`, and not `./ICostModel.sol`. Personally I prefer this because it's more clear, and simplifies moving files around.

When running `slither .` on RootRepo I receive the following error. Changing import paths from absolute to relative solves the issue. The repo compiles successfully with `forge build`, but it seems slither has issues resolving the remappings, what I believe is happening is:
- It can't find `src/interfaces/ICostModel.sol`, because that doesn't exist (i.e. `RootRepo/src/interfaces/ICostModel.sol` is where that's pointing)
- It should be looking in `RootRepo/lib/RepoModels/lib/RepoInterfaces/src/interfaces/ICostModel.sol`

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/crytic_compile/platform/foundry.py", line 117, in compile
    filename = convert_filename(
  File "/usr/local/lib/python3.10/site-packages/crytic_compile/utils/naming.py", line 117, in convert_filename
    raise InvalidCompilation(f"Unknown file: {filename}")
crytic_compile.platform.exceptions.InvalidCompilation: Unknown file: src/interfaces/ICostModel.sol

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/slither/__main__.py", line 826, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/usr/local/lib/python3.10/site-packages/slither/__main__.py", line 86, in process_all
    compilations = compile_all(target, **vars(args))
  File "/usr/local/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/usr/local/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/crytic_compile/platform/foundry.py", line 124, in compile
    raise InvalidCompilation(txt)
crytic_compile.platform.exceptions.InvalidCompilation: Unknown file: src/interfaces/ICostModel.sol
Something went wrong, please open an issue in https://github.com/crytic/crytic-compile
Error in .
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/crytic_compile/platform/foundry.py", line 117, in compile
    filename = convert_filename(
  File "/usr/local/lib/python3.10/site-packages/crytic_compile/utils/naming.py", line 117, in convert_filename
    raise InvalidCompilation(f"Unknown file: {filename}")
crytic_compile.platform.exceptions.InvalidCompilation: Unknown file: src/interfaces/ICostModel.sol

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/slither/__main__.py", line 826, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/usr/local/lib/python3.10/site-packages/slither/__main__.py", line 86, in process_all
    compilations = compile_all(target, **vars(args))
  File "/usr/local/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/usr/local/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/crytic_compile/platform/foundry.py", line 124, in compile
    raise InvalidCompilation(txt)
crytic_compile.platform.exceptions.InvalidCompilation: Unknown file: src/interfaces/ICostModel.sol
Something went wrong, please open an issue in https://github.com/crytic/crytic-compile
```

**Comment by 0xalpharush** [comment]
Would you see if the latest release fixes this @mds1 ?

**Comment by mds1** [comment]
I _think_ so, but the above repo was refactored to use relative paths so I'm not 100% certain. From my perspective I'll consider it fixed for now and will comment here if it comes up again
