### ISSUE TITLE
Crytic-compile doesn't handle single-file compilation with foundry

### ISSUE THREAD

**Issue by bsamuels453** [crytic/crytic-compile#313]
Repro steps:
1. Initialize a new empty foundry project
2. Run `crytic-compile --compile-force-framework foundry ./test/Counter.t.sol`

Result:
```
INFO:CryticCompile:'forge build --extra-output abi --extra-output userdoc --extra-output devdoc --extra-output evm.methodIdentifiers --force' running
Traceback (most recent call last):
  File "/Users/bsamuels/.pyenv/versions/reporting/bin/crytic-compile", line 8, in <module>
    sys.exit(main())
  File "/Users/bsamuels/.pyenv/versions/3.8.13/envs/reporting/lib/python3.8/site-packages/crytic_compile/__main__.py", line 193, in main
    compilations = compile_all(**vars(args))
  File "/Users/bsamuels/.pyenv/versions/3.8.13/envs/reporting/lib/python3.8/site-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/Users/bsamuels/.pyenv/versions/3.8.13/envs/reporting/lib/python3.8/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/Users/bsamuels/.pyenv/versions/3.8.13/envs/reporting/lib/python3.8/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/Users/bsamuels/.pyenv/versions/3.8.13/envs/reporting/lib/python3.8/site-packages/crytic_compile/platform/foundry.py", line 80, in compile
    with subprocess.Popen(
  File "/Users/bsamuels/.pyenv/versions/3.8.13/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/bsamuels/.pyenv/versions/3.8.13/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
NotADirectoryError: [Errno 20] Not a directory: './test/Counter.t.sol'
```

This issue was discovered while using Echidna on a foundry project. Echidna calls crytic-compile requesting that the single file be built.

For what it's worth, the compile fails even if not forcing foundry as the framework. This is because the foundry remappings can't be resolved, but I think that's probably expected behavior.

**Comment by bsamuels453** [comment]
Was able to fix my echidna usage by using `echidna-test . --contract <contractname> --config ./echidna.yaml` instead of `echidna-test <contractpath> --contract <contractname> --config ./echidna.yaml`

Not sure if it's worth keeping open as a bug for crytic-compile

**Comment by montyly** [comment]
Yes this is the actual expected behaviour. crytic-compile, and related tools, expect the main directory for projects that use a compilation framework
