### ISSUE TITLE
Error "Solidity version not found" is misleading

### ISSUE THREAD

**Issue by montyly** [crytic/crytic-compile#45]
https://github.com/crytic/crytic-compile/blob/758ce452eecce6e1cfa1a843c46b1268629fd468/crytic_compile/platform/truffle.py#L211-L228

In 99% of the case, the issue is that `truffle` is not found

**Comment by ggrieco-tob** [comment]
This is an interesting issue. Running crytic-compile without truffle (and disabling npx) will result in this error:

```
$ crytic-compile . --npx-disable
Traceback (most recent call last):
  File "/home/g/.local/bin/crytic-compile", line 11, in <module>
    load_entry_point('crytic-compile==0.1.4', 'console_scripts', 'crytic-compile')()
  File "/home/g/.local/lib/python3.6/site-packages/crytic_compile-0.1.4-py3.6.egg/crytic_compile/__main__.py", line 118, in main
    compilations = compile_all(**vars(args))
  File "/home/g/.local/lib/python3.6/site-packages/crytic_compile-0.1.4-py3.6.egg/crytic_compile/crytic_compile.py", line 83, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/home/g/.local/lib/python3.6/site-packages/crytic_compile-0.1.4-py3.6.egg/crytic_compile/crytic_compile.py", line 161, in __init__
    self._compile(target, **kwargs)
  File "/home/g/.local/lib/python3.6/site-packages/crytic_compile-0.1.4-py3.6.egg/crytic_compile/crytic_compile.py", line 744, in _compile
    self._platform.compile(self, target, **kwargs)
  File "/home/g/.local/lib/python3.6/site-packages/crytic_compile-0.1.4-py3.6.egg/crytic_compile/platform/truffle.py", line 63, in compile
    version, compiler = _get_version(base_cmd, cwd=target)
  File "/home/g/.local/lib/python3.6/site-packages/crytic_compile-0.1.4-py3.6.egg/crytic_compile/platform/truffle.py", line 214, in _get_version
    cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, cwd=cwd
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'truffle': 'truffle'
```
